//THIS IS FOR THE ADMIN LOGIN CONSTANTS
export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST'
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS'
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL'
//FOLLOWING IS FOR THE LOGOUT BY THE ADMIN OR THE OTHER COMMON LOGGED IN TEACHERS
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT'
//FOLLOWING ARE FOR DELETING THE STUDEN
