//THIS IS FOR THE ADMIN LOGIN CONSTANTS
export const TEACHER_LOGIN_REQUEST = 'TEACHER_LOGIN_REQUEST'
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS'
export const TEACHER_LOGIN_FAIL = 'TEACHER_LOGIN_FAIL'
//FOLLOWING IS FOR THE LOGOUT BY THE ADMIN OR THE OTHER COMMON LOGGED IN TEACHERS
export const TEACHER_LOGOUT = 'TEACHER_LOGOUT'
//FOLLOWING ARE FOR DELETING THE STUDEN
